#!/bin/csh
set base=`pwd`

set finp=$1
set ntraj=$2
set nstep=$3
set nrec=$4
set wtime=$5

set rundir=$finp.'$PBS_JOBID'
set nrand1=$$

cat > pbs.$$<<EOF
###
#PBS -l nodes=1:ppn=4
#PBS -l walltime=$wtime\:00:00
#PBS -N dmd
#PBS -r n
#PBS -c n
#PBS -m n
#PBS -joe
#PBS -koe
#PBS -V
#PBS -S /bin/csh
#PBS -q xeon16

set nrand2=\$\$
cd /scratch/quchen

mkdir $rundir
cd $rundir
hostname -s >> $finp.node

cp $finp.node $base
cp $base/* .
./dmd.x $finp $ntraj $nstep $nrec $nrand1 \$nrand2
cp * $base
cd ..

rm -rf $rundir

EOF

qsub pbs.$$
rm pbs.$$
