#!/bin/bash

#This is the fold to store fitting coefficients. Newly generated coefficent files are in format `.out`. However, only `.dat` file can be called when using coefficient. By default, the transformation has been implemented in fitting routine, all `.out` will be moved into to `.dat` files. However, users can also do this manually if one use his or her own configured fitting routine.

#pcf-x1.dat,pcf-y1.dat and pcf-z1.dat are the three only files required to generate all other higher symmetry files. Thoses three files shall never be removed.

for x in *.out
do
  base=${x%.out}
  mv $x $base.dat
done

echo ''
echo 'All .out files have been transformed to .dat files successfully'
