#!/bin/csh
set order = 5
set a = 2
set b = 2
set c = 1
set d = 0
set e = 0
set f = 0
set sym =($a $b $c $d $e $f)


cd emsa
make
cp msa ../
cd ../
./msa $order $sym 
./postemsa.pl $order $sym
./derivative.pl $order $sym
echo 'Total coefficient:'
 aa = $(($ head -n 8 basis.f90 | tail -n 1 ) 2>&1 )
echo $aa
